VERSION=2.1.7.1
PACKAGE=zcs-lib-itext-2
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=base
ARCHITECTURE=All
PRIORITY=optional
DEPENDS=
DESCRIPTION=pdf rendering library
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
REDMINE_UPLOAD_PROJECT=zcs-lib-itext
